client:
    client-001:
        publicKey:
            MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCwIYzsZelLv4g9LCjMfthYCHB7
            4KDq/bZxwa+u4aky+9B+yvQSXjW1Q8BG4xsyEdi5TrOmCFVUEQdKWziRM0Afn007
            NcRa7ubZVgF1WSp9QDa/5TApA0bQjmOxy+0gqzWGtv30Eei6Oog4gOGD69nQVnbC
            z+cPHiwn9CWGfcbj6wIDAQAB